spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/multitenant
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        multi_tenant_connection_provider: com.example.multitenant.config.MultiTenantProvider
        tenant_identifier_resolver: com.example.multitenant.config.MultiTenantResolver
        default_schema: public
        multiTenancy: SCHEMA
    open-in-view: false

  application:
    tenants: alibaba,amazon,wasabi
